### ISSUE TITLE
Appropriate Credit

### ISSUE THREAD

**Issue by coatless** [leg-ufpr/legtheme#1]
Please link back to the `uiucthemes` package as this project largely copies the work that I've done. Otherwise, this is a clear violation of the MIT license and _not_ really good behavior in the FOSS community.

**Comment by fernandomayer** [comment]
Yes, of course. I've just started modifying it yesterday and still working on some things. It is not finished yet, but the next commit will bring the proper credits. 

Thanks for sharing, by the way.

**Comment by fernandomayer** [comment]
Updated by 7798345 and subsequent commits.

**Comment by coatless** [comment]
@fernandomayer thank you for adding attribution! 

I hope the theme works out nicely for you!
